### ISSUE TITLE
Strange list_get behavior

### ISSUE THREAD

**Issue by MeWhenI** [polygolf-lang/polygolf#271]
**Describe the bug**
Code with multiple list-gets has unpredictable effects on output.

**To Reproduce**
Compiling
```polygolf
list_get (list "ABC" "123") 1;
list_get (list "DEF" "456") 1;
println (list_get (list "GHI" "789" ) 1);
```
with `-l py`
produces
```py
["ABC","123"][1]
["DEF","456"][1]
print(["GHI","789"][1])
```
Deleting either of the first 2 lines causes it to produce
```py
print("789\n")
```

**Expected behavior**
The lines of code before the last one should not affect how golfed the last line is. Also, note that deleting even one of the first two lines causes the other to not be outputted at all.

I suspect this may have nothing to do with the `list_get` op and just be about some ceiling being hit on the number of golf plugins that can be run, but at the moment I'm not sure.

**Comment by MichalMarsalek** [comment]
This is caused by a malfunctioning interpreter / hardcode plugin.
We can see that Polygolf is [not able to evaluate the output of the original program](https://polygolf-lang.github.io/?source=list_get%20(list%20%22ABC%22%20%22123%22)%201%3B%0Alist_get%20(list%20%22DEF%22%20%22456%22)%201%3B%0Aprintln%20(list_get%20(list%20%22GHI%22%20%22789%22%20)%201)%3B&language=Text&objective=bytes&getAllVariants=false), but it [is able to evaluate the program with one of the lines deleted](https://polygolf-lang.github.io/?source=list_get%20(list%20%22ABC%22%20%22123%22)%201%3B%0Aprintln%20(list_get%20(list%20%22GHI%22%20%22789%22%20)%201)%3B&language=Text&objective=bytes&getAllVariants=false), hence being able to reduce the whole program to just hardcoding the output.

**Comment by MichalMarsalek** [comment]
Ah, this is simply caused by the [js output](https://polygolf-lang.github.io/?source=list_get%20(list%20%22ABC%22%20%22123%22)%201%3B%0Alist_get%20(list%20%22DEF%22%20%22456%22)%201%3B%0Aprintln%20(list_get%20(list%20%22GHI%22%20%22789%22%20)%201)%3B&language=Javascript&objective=bytes&getAllVariants=false) not being valid javascript. The first line needs  a semicolon. So this ain't a big issue, since you don't really need to use discards like this. Alternatively we can ban implicit discards outside of tests as I was considering doing several times.
Are there golf relevant cases of the automatic semicolon insertion failing?

**Comment by MeWhenI** [comment]
No relevant cases outside of testing that I'm aware of, I just stumbled across this while testing #252

**Comment by MichalMarsalek** [comment]
We can just output single line javascript, but that would make tests slightly less readable.

**Comment by MeWhenI** [comment]
I think "semicolons only where they are strictly needed and newlines elsewhere" is a common enough golfing style to be justifiable. It trades off a bit of simplicity and consistency but maintains the readability benefits as much as possible.

**Comment by MeWhenI** [comment]
On second thought, there is at least one golf application of a statement starting with an open bracket:
```js
[a,b]=`1 2`.split` `
```

**Comment by MichalMarsalek** [comment]
> On second thought, there is at least one golf application of a statement starting with an open bracket:
> 
> ```js
> [a,b]=`1 2`.split` `
> ```

Ok, I will patch js to replace newlines with semicolons where needed.
